name: cli-name
on: [push, pull_request]

jobs:
  cli-name:
    runs-on: ubuntu-latest
    steps:
      - name: Use Code Climate
        uses: remarkablemark/setup-codeclimate@v2
        with:
          cli-name: codeclimate

      - name: Get binary
        run: command -v codeclimate
