name: javascript
on: [push, pull_request]

jobs:
  javascript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change directory
        run: cd javascript

      - name: Install dependencies
        run: npm install

      - name: Use Code Climate
        uses: remarkablemark/setup-codeclimate@v1

      - name: Run tests
        run: |
          cc-test-reporter before-build
          npm test
          cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
