name: linux
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Use Code Climate
        uses: remarkablemark/setup-codeclimate@v1

      - name: Get binary
        run: command -v cc-test-reporter

      - name: Check version
        run: cc-test-reporter --version

      - name: Show help
        run: cc-test-reporter --help
